server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 10.10.50.189:8848
    gateway:
      discovery: #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator: #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: pyy-system-base-server  # 唯一标识，通常使用服务id
          uri: lb://pyy-system-base-server  # 目标URL，lb代表从注册中心获取服务
          predicates:
            # Predicate集合
            - Path=/v1/base-server/**  # 匹配转发路径
          filters:
          - StripPrefix=2 # 从第几级开始转发，数字从0开始
# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        # 暴露所有监控端点
        include: '*'
  endpoint:
    health:
      # 总是显示健康检测详情
      show-details: always